spring.datasource.url=jdbc:mysql://localhost:3306/assets_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1204
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

gemini.api.base-url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-lite:generateContent?key=
gemini.api.key=AIzaSyDXCeavQrlaqyc57sTd5H7TSwafwq2Dt5A

stockdata.api.key=3QOrDIdZYnDtbnw9ZNKM4MrURqj3S8h2j6KLEv8a
